package com.flowpay.FlowPay.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Getter;
import lombok.Setter;

/**
 * DTO for verifying a Razorpay payment after the client-side checkout completes.
 *
 * <p>Razorpay's frontend SDK returns payment details in snake_case
 * (e.g. {@code razorpay_payment_id}). The {@link JsonProperty} annotations
 * ensure Jackson deserializes these fields correctly from the incoming JSON body.</p>
 *
 * <p>All three fields are required to construct the HMAC-SHA256 signature
 * payload and validate it against Razorpay's signed signature.</p>
 */
@Getter
@Setter
public class PaymentVerificationRequest {

    /**
     * The Razorpay Order ID generated at the time of order creation
     * (e.g. {@code order_XXXXXXXXXX}).
     */
    @JsonProperty("razorpay_order_id")
    private String razorpayOrderId;

    /**
     * The Razorpay Payment ID returned by the Razorpay checkout after
     * the user completes payment (e.g. {@code pay_XXXXXXXXXX}).
     *
     * <p><b>Fix:</b> This field was previously not deserialised from
     * {@code razorpay_payment_id} because the {@code @JsonProperty} annotation
     * was missing. Without it, the field arrived as {@code null}, causing
     * signature verification to always fail.</p>
     */
    @JsonProperty("razorpay_payment_id")
    private String razorpayPaymentId;

    /**
     * The HMAC-SHA256 signature generated by Razorpay for the payment event.
     * Used to verify the authenticity of the payment response.
     */
    @JsonProperty("razorpay_signature")
    private String razorpaySignature;
}
